#!/usr/bin/env ruby

mutations_hg19 = Rbbt.examples.affected_genes["10_000"].mutations.find(:lib).list
mutations_hg18 = Rbbt.examples.affected_genes.may2009.mutations.find(:lib).list

require 'rbbt/workflow'

Workflow.require_workflow "Sequence"

mutations = {}

mutations["Hsa/may2009"] = mutations_hg18
mutations["Hsa/jun2011"] = mutations_hg19
mutations["Hsa/jan2013"] = mutations_hg19
mutations["Hsa/dec2013"] = mutations_hg19

jobs = []
mutations.keys.each do |organism|

  params = { :mutations => mutations[organism].dup, :organism => organism, :watson => false}

  job = Sequence.job(:mutated_isoforms, "BOOTSTRAP-#{organism}", params)
  jobs << job

  params = { :positions => mutations[organism].dup, :organism => organism }
  job = Sequence.job(:exon_junctions, "BOOTSTRAP-#{organism}", params)
  jobs << job

  params = { :positions => mutations[organism].dup, :organism => organism }
  job = Sequence.job(:genes, "BOOTSTRAP-#{organism}", params)
  jobs << job
end

jobs.each do |job|
  job.run(true).grace
end

Step.wait_for_jobs(jobs)


